name: Configure AWS CLI

on:
  workflow_dispatch:  # You can also use `push` or `pull_request`

jobs:
  configure-aws:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install AWS CLI v2
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
          aws --version

      - name: Configure AWS CLI using GitHub Secrets
        run: |
          mkdir -p ~/.aws

          cat > ~/.aws/credentials <<EOL
          [default]
          aws_access_key_id = ${AWS_ACCESS_KEY_ID}
          aws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}
          EOL

          cat > ~/.aws/config <<EOL
          [default]
          region = ap-south-1
          output = json
          EOL

          echo "✅ AWS CLI configured successfully."
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
